<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die(); ?>
<?
$aMenuLinks = Array(
    Array(
        "Шмонпания",
        "company/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новости",
        "news/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Продукция",
        "products/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Услуги",
        "services/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Партнеры",
        "/partners/",
        Array(),
        Array(),
        ""
    )
);
?>